---
- name: Install and start Nginx server
  hosts: web_servers
  # remote_user: toor

  vars:
    nginx_package: nginx
    nginx_service: nginx

  tasks:
    - name: Installer Nginx
      apt:
        name: "{{ nginx_package }}"
        state: present
      when: ansible_os_family == "Debian" 

    - name: Démarrer le service Nginx
      service:
        name: "{{ nginx_service }}"
        state: started

  handlers:
    - name: Redémarrer Nginx si la configuration change
      service:
        name: "{{ nginx_service }}"
        state: restarted
      listen: "reload_configuration"


- name: MariaDB installation
  hosts: database_servers
  # remote_user: toor

  tasks:
    - name: "mariadb-server installation"
      apt:
        name: "mariadb-server,python3-mysqldb"
        state: "present"
      when: ansible_os_family == "Debian" 

    # Active le service MariaDB
    - name: "start mariadb service"
      service:
        name: "mariadb"
        state: "started"
        enabled: yes
        

    # Restart mariadb
    - name: "restart mariasdb"
      service:
        name: "mariadb"
        state: restarted