# To deploy an application that allow to create recipes and checklist for foods and grocery shoping. 
# You can access it locally with the command `k port-forward pods/mealie-podname-truc 9000`

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v1.3.2
        name: mealie
        ports:
          - containerPort: 9000
