---
# handlers file for bind9
  - name: Start bind9
    ansible.builtin.service: 
      name: named
      state: started
  
  - name: Enable bind9
    ansible.builtin.service:
      name: named
      enabled: true

  - name: Restart bind9
    ansible.builtin.service:
      name: httpd
      state: restarted
    
  - name: Reload bind9
    ansible.builtin.service:
      name: named
      state: reloaded
      
  - name: reload apparmor bind9 profile
   shell: /sbin/apparmor_parser -r /etc/apparmor.d/usr.sbin.named

  - name: reload bind9
    service: name=bind9 state=reloaded