---
- name: Verify setup
  hosts: all

  tasks:
    - name: Make sure that service is started
      ansible.builtin.service:
        name: mariadb
        state: started
      register: status
      failed_when: status.changed

    - name: Make sure that service is enabled
      ansible.builtin.service:
        name: mariadb
        state: enabled
      register: status
      failed_when: status.changed

- name: Verify replication
  hosts: replica
  tasks:
    - name: Check that test db exist (created only on primary node)
      ansible.builtin.shell: |
        mariadb -Bse 'SHOW DATABASES' | grep -q '^{{ item }}$'
      loop:
        - db

    - name: Get replica status
      ansible.builtin.shell: |
        mariadb -Bse 'SHOW SLAVE STATUS\G'
      register: replica_status

    - name: Check that replication is working
      ansible.builtin.assert:
        that:
          - "'Waiting for master to send event' in replica_status.stdout"
        msg: "{{ replica_status.stdout }}"
