galaxy_info:
  author: ton_nom  
  description: Ansible role to install and start MariaDB
  company: devacteur
  license: Proprietary
  min_ansible_version: '2.9'  

  platforms:
    - name: Debian
      versions:
        - bookworm 

  galaxy_tags: 
    - database
    - mariadb
    - sql-database

dependencies: [] 
