---
# tasks file for php
---
- name: Install PHP 8.1 on Debian from sury.org repository
  hosts: php-apache
  become: true
  tasks:
    - name: Install necessary packages for managing the repository over HTTPS
      apt:
        name: "{{ package }}"
        state: present
      loop: 
          - apt-transport-https
          - lsb-release
          - curl
      update_cache: true

    - name: Download and install the GPG key for the sury.org repository
      get_url:
        url: https://packages.sury.org/php/apt.gpg
        dest: /usr/share/keyrings/deb.sury.org-php.gpg

    - name: Add sury.org repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ {{ ansible_lsb.codename }} main
        filename: sury-php

    - name: Update apt cache after adding new repository
      apt:
        update_cache: true

    - name: Remove existing PHP packages and configurations
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - php*
        - libapache2-mod-php
      ignore_errors: yes

    - name: Install PHP 8.1 and commonly used extensions
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libapache2-mod-php8.1
        - php8.1
        - php8.1-curl
        - php8.1-gd
        - php8.1-intl
        - php8.1-memcache
        - php8.1-xml
        - php8.1-zip
        - php8.1-mbstring

    - name: Restart Apache to apply changes
      systemd:
        name: apache2
        state: restarted

    - name: Show PHP version
      ansible.builtin.shell: php -v
