apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web-pod
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  containers:
    - name: apache-container
      image: httpd:latest
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          name: shared-volume
      command: ["httpd", "-DFOREGROUND", "-C", "Listen 8080"]

    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: shared-volume
      # Vous pouvez ajouter ici une configuration de redirection dans Nginx si nécessaire
