---
# tasks file for bind9
- name: Install tasks for bind9
  hosts: bind9
  become: true
  tasks:

    - name: Check OS (bind9 - debian)
      fail: msg="Not a Debian based system!"
      when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

    - name: Installation for Debian like systems
      include_tasks: debian.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install dependencies packages
      apt: 
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - bind9 
        - bind9utils 
        - bind9-doc 
        - dnsutils

    - name: Show bind9 version
      ansible.builtin.shell: sudo named -v
      
