---
# Active le service MariaDB
- name: "start mariadb service"
  service:
    name: "mariadb"
    state: "started"
    enabled: yes

# # Actuve l'écoute sur tous les ports IPv4
# - name: "change 50-server.cnf"
#   command:
#     /usr/bin/sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf

# Restart mariadb
- name: "restart mariasdb"
  service:
    name: "mariadb"
    state: restarted